-- Comprehensive Database Schema Analysis for BusBuddy
-- This script will analyze all tables and their column types

-- Activities Table
SELECT 'Activities' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Activities' 
ORDER BY ORDINAL_POSITION;

-- ActivityLogs Table  
SELECT 'ActivityLogs' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ActivityLogs' 
ORDER BY ORDINAL_POSITION;

-- ActivitySchedule Table
SELECT 'ActivitySchedule' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'ActivitySchedule' 
ORDER BY ORDINAL_POSITION;

-- Drivers Table
SELECT 'Drivers' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Drivers' 
ORDER BY ORDINAL_POSITION;

-- Fuel Table
SELECT 'Fuel' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Fuel' 
ORDER BY ORDINAL_POSITION;

-- Maintenance Table
SELECT 'Maintenance' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Maintenance' 
ORDER BY ORDINAL_POSITION;

-- Routes Table
SELECT 'Routes' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Routes' 
ORDER BY ORDINAL_POSITION;

-- RouteStops Table
SELECT 'RouteStops' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'RouteStops' 
ORDER BY ORDINAL_POSITION;

-- Schedules Table
SELECT 'Schedules' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Schedules' 
ORDER BY ORDINAL_POSITION;

-- SchoolCalendar Table
SELECT 'SchoolCalendar' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'SchoolCalendar' 
ORDER BY ORDINAL_POSITION;

-- Students Table
SELECT 'Students' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Students' 
ORDER BY ORDINAL_POSITION;

-- Tickets Table
SELECT 'Tickets' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Tickets' 
ORDER BY ORDINAL_POSITION;

-- Vehicles Table
SELECT 'Vehicles' as TableName, COLUMN_NAME, DATA_TYPE, CHARACTER_MAXIMUM_LENGTH, IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Vehicles' 
ORDER BY ORDINAL_POSITION;
