//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusBuddy.WPF.Resources.Strings
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BusBuddy.WPF.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Action_Add
        {
            get
            {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Action_Cancel
        {
            get
            {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Action_Close
        {
            get
            {
                return ResourceManager.GetString("Action_Close", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete
        {
            get
            {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit
        {
            get
            {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Action_Export
        {
            get
            {
                return ResourceManager.GetString("Action_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Action_Filter
        {
            get
            {
                return ResourceManager.GetString("Action_Filter", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Action_Import
        {
            get
            {
                return ResourceManager.GetString("Action_Import", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Action_Print
        {
            get
            {
                return ResourceManager.GetString("Action_Print", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Action_Refresh
        {
            get
            {
                return ResourceManager.GetString("Action_Refresh", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save
        {
            get
            {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Action_Search
        {
            get
            {
                return ResourceManager.GetString("Action_Search", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bus Buddy.
        /// </summary>
        public static string AppTitle
        {
            get
            {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to School Transportation Management System.
        /// </summary>
        public static string AppSubtitle
        {
            get
            {
                return ResourceManager.GetString("AppSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Version 1.0.0.
        /// </summary>
        public static string AppVersion
        {
            get
            {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🏠 Dashboard.
        /// </summary>
        public static string Nav_Dashboard
        {
            get
            {
                return ResourceManager.GetString("Nav_Dashboard", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 👨‍🎓 Students.
        /// </summary>
        public static string Nav_Students
        {
            get
            {
                return ResourceManager.GetString("Nav_Students", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🚌 Buses.
        /// </summary>
        public static string Nav_Buses
        {
            get
            {
                return ResourceManager.GetString("Nav_Buses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 👨‍💼 Drivers.
        /// </summary>
        public static string Nav_Drivers
        {
            get
            {
                return ResourceManager.GetString("Nav_Drivers", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🛣️ Routes.
        /// </summary>
        public static string Nav_Routes
        {
            get
            {
                return ResourceManager.GetString("Nav_Routes", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📅 Schedules.
        /// </summary>
        public static string Nav_Schedules
        {
            get
            {
                return ResourceManager.GetString("Nav_Schedules", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🔧 Maintenance.
        /// </summary>
        public static string Nav_Maintenance
        {
            get
            {
                return ResourceManager.GetString("Nav_Maintenance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⛽ Fuel.
        /// </summary>
        public static string Nav_Fuel
        {
            get
            {
                return ResourceManager.GetString("Nav_Fuel", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 📊 Activity.
        /// </summary>
        public static string Nav_Activity
        {
            get
            {
                return ResourceManager.GetString("Nav_Activity", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🎫 Tickets.
        /// </summary>
        public static string Nav_Tickets
        {
            get
            {
                return ResourceManager.GetString("Nav_Tickets", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ⚙️ Settings.
        /// </summary>
        public static string Nav_Settings
        {
            get
            {
                return ResourceManager.GetString("Nav_Settings", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 🤖 AI Assistant.
        /// </summary>
        public static string Nav_XAIChat
        {
            get
            {
                return ResourceManager.GetString("Nav_XAIChat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Label_Loading
        {
            get
            {
                return ResourceManager.GetString("Label_Loading", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Student Management.
        /// </summary>
        public static string Student_Title
        {
            get
            {
                return ResourceManager.GetString("Student_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Bus Management.
        /// </summary>
        public static string Bus_Title
        {
            get
            {
                return ResourceManager.GetString("Bus_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Driver Management.
        /// </summary>
        public static string Driver_Title
        {
            get
            {
                return ResourceManager.GetString("Driver_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Route Management.
        /// </summary>
        public static string Route_Title
        {
            get
            {
                return ResourceManager.GetString("Route_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Schedule Management.
        /// </summary>
        public static string Schedule_Title
        {
            get
            {
                return ResourceManager.GetString("Schedule_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Maintenance Tracking.
        /// </summary>
        public static string Maintenance_Title
        {
            get
            {
                return ResourceManager.GetString("Maintenance_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Fuel Management.
        /// </summary>
        public static string Fuel_Title
        {
            get
            {
                return ResourceManager.GetString("Fuel_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Activity Logging.
        /// </summary>
        public static string Activity_Title
        {
            get
            {
                return ResourceManager.GetString("Activity_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket Management.
        /// </summary>
        public static string Ticket_Title
        {
            get
            {
                return ResourceManager.GetString("Ticket_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings_Title
        {
            get
            {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI Assistant.
        /// </summary>
        public static string XAI_Title
        {
            get
            {
                return ResourceManager.GetString("XAI_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Type your message here....
        /// </summary>
        public static string XAI_TypeMessage
        {
            get
            {
                return ResourceManager.GetString("XAI_TypeMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string XAI_Send
        {
            get
            {
                return ResourceManager.GetString("XAI_Send", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Clear Chat.
        /// </summary>
        public static string XAI_ClearChat
        {
            get
            {
                return ResourceManager.GetString("XAI_ClearChat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to AI is thinking....
        /// </summary>
        public static string XAI_Thinking
        {
            get
            {
                return ResourceManager.GetString("XAI_Thinking", resourceCulture);
            }
        }
    }
}
